name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: |
          g++ main.cpp -o test
          ./test

      - name: Run clang-format
        run: |
          clang-format --version
          clang-format --style=file -i *.hpp *.cpp
          git status
          FILES=$(git ls-files --full-name *.hpp *.cpp)
          echo "FILES: $FILES"
          if [[ -n $FILES ]]; then
            echo 'formatting changes detected'
            git config --global user.name 'iamazeem'
            git config --global user.email 'iamazeem@users.noreply.github.com'
            git add $FILES
            git commit -m "Automatic clang-format update by CI."
            git push
          fi
          echo '--- [DONE] ---'
