name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: |
          g++ main.cpp -o test
          ./test

      - name: Run clang-format
        run: |
          clang-format --version
          clang-format --style=file -i *.hpp *.cpp
          DIFF=$(git diff)
          if [[ -z $DIFF ]]; then
            echo "Nothing changed! Files are already formatted!"
          else
            echo "Running git status"
            git status
            echo "--- git diff STARTS ---"
            echo $DIFF
            echo "---- git diff ENDS ----"
            FILES=$(git ls-files --full-name *.hpp *.cpp)
            echo "FILES:"
            echo $FILES
            echo "Pushing newly formatted files"
            git config --global user.name 'iamazeem'
            git config --global user.email 'iamazeem@users.noreply.github.com'
            git add $FILES
            git commit -m "Automatic clang-format update by CI."
            git push
          fi
          echo '--- [DONE] ---'
