name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: |
          g++ main.cpp -o test
          ./test

      - name: Run clang-format
        run: |
          clang-format --version
          clang-format --style=file -i *.hpp *.cpp
          git status
          FILES=$(git ls-files --full-name *.hpp *.cpp)
          if [[ -n $FILES ]]; then
            echo 'formatting changes detected'
            git add .
            git commit -m "ci update: clang-format applied"
            git push
          fi
          echo '--- [DONE] ---'

